// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Ez_Tech.Model
{
    public partial class EztechdbContext : DbContext
    {
        public EztechdbContext()
        {
        }

        public EztechdbContext(DbContextOptions<EztechdbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Hjælpere> Hjælpere { get; set; }
        public virtual DbSet<Kunder> Kunder { get; set; }
        public virtual DbSet<Opgaver> Opgaver { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity<Hjælpere>(entity =>
            {
                entity.Property(e => e.ID).ValueGeneratedNever();

                entity.Property(e => e.Email)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Kodeord)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Navn)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.TelefonNummer)
                    .IsRequired()
                    .HasMaxLength(11)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Kunder>(entity =>
            {
                entity.HasKey(e => e.KundeID)
                    .HasName("PK__Kunder__7F871DE18C09D9BD");

                entity.Property(e => e.KundeID).ValueGeneratedNever();

                entity.Property(e => e.KundeAdresse)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.KundeNavn)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.KundeNummer)
                    .IsRequired()
                    .HasMaxLength(11)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Opgaver>(entity =>
            {
                entity.Property(e => e.ID).ValueGeneratedNever();

                entity.Property(e => e.Beskrivelse)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.HasOne(d => d.Kunde)
                    .WithMany(p => p.Opgaver)
                    .HasForeignKey(d => d.KundeID)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Opgaver__KundeID__286302EC");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}