// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Ez_Tech.Model
{
    public partial class Hjælpere
    {
        public int ID { get; set; }
        public string Navn { get; set; }
        public string TelefonNummer { get; set; }
        public string Kodeord { get; set; }
        public string Email { get; set; }
        public bool IsAdmin { get; set; }

        public override string ToString()
        {
            return $"{ID} {Navn} {TelefonNummer} {Kodeord} {Email} {IsAdmin}";
        }
    }
}