// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Ez_Tech.Model
{
    public partial class Kunder
    {
        public Kunder()
        {
            Opgaver = new HashSet<Opgaver>();
        }

        public int KundeID { get; set; }
        public string KundeNavn { get; set; }
        public string KundeNummer { get; set; }
        public string KundeAdresse { get; set; }

        public virtual ICollection<Opgaver> Opgaver { get; set; }
    }
}