// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using Client.Annotations;

namespace Client.Model
{
    public partial class Kunder : INotifyPropertyChanged
    {
        #region Instancefield

        private int _kundeId;
        private string _kundeNavn;
        private string _kundeNummer;
        private string _kundeAdresse;

        

        #endregion

        #region Constructor

        public Kunder(int id, string kundenavn, string kundenummer, string kundeadresse)
        {
            _kundeId = id;
            _kundeNavn = kundenavn;
            _kundeNummer = kundenummer;
            _kundeAdresse = kundeadresse;

            Opgaver = new HashSet<Opgaver>();
        }

        public Kunder() {}

        #endregion

        #region Properties
        public int KundeID
        {
            get { return _kundeId;}
            set { _kundeId = value; OnPropertyChanged(nameof(KundeID)); }
        }
        public string KundeNavn
        {
            get { return _kundeNavn;}
            set { _kundeNavn = value; OnPropertyChanged(nameof(KundeNavn)); }
        }
        public string KundeNummer
        {
            get { return _kundeNummer;}
            set { _kundeNummer = value; OnPropertyChanged(nameof(KundeNummer));  }
        }
        public string KundeAdresse
        {
            get { return _kundeAdresse;}
            set { _kundeAdresse = value; OnPropertyChanged(nameof(KundeAdresse)); }
        }

        public virtual ICollection<Opgaver> Opgaver { get; set; }
        #endregion

        #region Method
        public override string ToString()
        {
            return $"{KundeID} {KundeNavn} {KundeNummer} {KundeAdresse}";
        }
        public event PropertyChangedEventHandler PropertyChanged;
        [NotifyPropertyChangedInvocator]
        protected virtual void OnPropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
        #endregion

    }
}